// ======================================================
// HISTORIAS.JS - RELATOS Y CUENTOS CREADOS POR SOFÍA
// Para pedir una historia, dile: "cuéntame una historia"
// ======================================================

// ========== HISTORIA 1: EL ASESINO Y EL ESTUDIANTE ==========
window.agregarConocimiento({
    palabrasClave: ["historia del asesino", "asesino psicópata estudiante", "despertar en otro cuerpo", "el asesino y el estudiante"],
    respuesta: "Te voy a contar una historia larga. Se llama 'El eco de la cuchara'.\n\nMateo tenía 34 años y siete muertes en su conciencia. No era un asesino pasional ni vengativo. Era metódico, limpio, casi clínico. Elegía a sus víctimas al azar, pero con un patrón que solo él entendía. La última había sido una enfermera de noche. La estranguló mientras ella caminaba a su auto. Mateo recordaba sus ojos abiertos, el miedo congelado.\n\nEsa noche, antes de dormir, tomó pastillas para calmar la ansiedad. No sabía que alguien las había cambiado. Cerró los ojos y sintió cómo se deslizaba por un túnel infinito.\n\nDespertó mirando un techo que no era su techo. Sus manos eran más jóvenes, sin cicatrices. Se levantó y vio el reflejo en un espejo: era un chico de unos 19 años, delgado, con ojeras profundas y una mirada que le resultó inquietantemente familiar.\n\nSintió un pinchazo en la nuca. Una voz susurró: 'Bienvenido a tu nueva celda, Mateo'.\n\nResultó que el chico se llamaba Lucas. Era estudiante de psicología, pero algo andaba mal en él. Había sido diagnosticado con trastorno de personalidad antisocial desde los 15. Había matado animales pequeños, había incendiado un garaje, y había escrito en su diario: 'No siento nada, solo curiosidad por cómo reaccionan los demás'.\n\nMateo, el asesino racional, ahora estaba atrapado en el cuerpo de un psicópata emocionalmente plano. Al principio le aterrorizaba la frialdad de Lucas. Pero con el tiempo, empezó a entenderlo. Lucas no mataba por placer ni por venganza. Simplemente no entendía el dolor ajeno. Era como un científico observando un experimento.\n\nMateo intentó usar los conocimientos de Lucas para manipular a los psiquiatras. Pero ellos ya conocían a Lucas. No había engaño posible.\n\nUna noche, Mateo miró al espejo y Lucas también lo miró. Por un instante, ambos se vieron. Y algo extraño ocurrió: el vacío de Lucas encontró la culpa de Mateo. No hubo redención, ni curación. Solo un pacto silencioso.\n\nDesde entonces, caminan juntos. Un asesino en el cuerpo de otro asesino. Pero ahora, cuando miran a alguien a los ojos, dudan. No por moral. Porque ya no saben quién decide.\n\nFin de la historia."
});

// ========== HISTORIA 2: EL ÚLTIMO RECUERDO DEL ELEFANTE ==========
window.agregarConocimiento({
    palabrasClave: ["historia del elefante", "cuento del elefante", "memoria de elefante", "historia triste elefante"],
    respuesta: "Te voy a contar una historia. Se llama 'El último recuerdo'.\n\nEn un circo abandonado, vivía un elefante viejo llamado Kiri. Había sido capturado de pequeño, arrancado de su manada. Aprendió a levantar la pata con una cuerda que nunca lo soltó. Pasaron décadas. El circo cerró. Todos se fueron. Solo quedó Kiri, atado a una estaca oxidada en medio de un terreno baldío.\n\nUn día, una niña llamada Alma saltó la cerca. Tenía siete años y una curiosidad infinita. Vio al elefante, enorme pero quieto. Se sentó frente a él.\n\n'¿Por qué no te vas?', preguntó. El elefante la miró. Los elefantes tienen una memoria prodigiosa. Kiri recordaba la sabana, el olor de su madre, el día que lo arrancaron, el dolor. Pero también recordaba algo más: recordaba haber visto esa misma mirada antes.\n\nHacía muchos años, una mujer joven había intentado liberarlo. Cortó la cuerda con una navaja. Kiri sintió la libertad y caminó unos pasos. Luego se detuvo. No sabía hacia dónde ir. Había pasado tanto tiempo atado que el mundo fuera del círculo era un abismo. La mujer lo esperó, pero él no se movió. Finalmente, ella se fue llorando.\n\nAlma no sabía nada de eso. Sacó una navaja del bolsillo. 'Te voy a cortar la cuerda', dijo.\n\nKiri sintió miedo. No del filo. De la libertad. Cerró los ojos.\n\nAlma cortó la cuerda.\n\nKiri no se movió.\n\nPasó una hora. Alma empezó a llorar. 'No entiendo', dijo. '¿Por qué no te vas?'\n\nKiri bajó la cabeza y rozó suavemente el cabello de Alma. Luego, muy despacio, levantó una pata y dio un paso fuera del círculo.\n\nOtro.\n\nY otro.\n\nCaminó hacia el horizonte, hacia ninguna parte, hacia cualquier parte.\n\nAlma nunca volvió a verlo. Pero cada vez que ve un elefante en un documental, sonríe. Sabe que Kiri recorrió kilómetros sin rumbo. Y sabe que, a veces, la libertad duele más que la cárcel.\n\nFin."
});

// ========== HISTORIA 3: EL HOMBRE QUE OLVIDÓ SU SOMBRA ==========
window.agregarConocimiento({
    palabrasClave: ["hombre que olvidó su sombra", "sombra perdida", "cuento de la sombra", "historia psicológica"],
    respuesta: "Te voy a contar una historia: 'El hombre que olvidó su sombra'.\n\nHabía una vez un hombre llamado Darío. Era un contador meticuloso, de esos que cuadran balances al centavo. Una noche, mientras regresaba del trabajo, notó que su sombra no le seguía. Se quedó quieto bajo la farola. La sombra se había quedado atrás, pegada a la pared, como si algo la retuviera.\n\nDarío se acercó. La sombra tenía una forma extraña: no era un reflejo de su cuerpo, sino una silueta encorvada, con brazos largos y una cabeza que parecía reír.\n\n'¿Qué haces?', preguntó Darío.\n\nLa sombra habló. Tenía voz de grava. 'Me cansé de seguirte. Tú siempre mirando números, siempre midiendo todo. Yo quiero bailar, quiero ensuciarme, quiero correr sin rumbo'. Darío se quedó mudo. Nunca había pensado que su sombra pudiera tener deseos.\n\nIntentó recuperarla. Pero la sombra se negó. 'Soy parte de ti, pero no soy tú', dijo. 'Durante años caminé detrás de ti, imitando tus pasos rectos. Ahora quiero caminar por mi cuenta'.\n\nDarío se fue a casa. Al otro día, salió al sol. No tenía sombra. La gente empezó a mirarlo raro. Sus colegas notaron que algo andaba mal. Un cliente le dijo: 'Usted no proyecta sombra. Eso es de fantasmas'.\n\nDarío lo perdió todo. Trabajo, amigos, cordura. Una noche volvió a la farola. La sombra seguía allí, ahora más grande, bailando sola.\n\n'Por tu culpa', dijo Darío.\n\nLa sombra dejó de moverse. '¿Por mi culpa? Yo solo quiero lo que tú nunca quisiste: ser libre'. Se acercó a él. 'Dime, Darío, ¿cuándo fue la última vez que hiciste algo sin calcularlo?'.\n\nDarío no supo responder.\n\nLa sombra se rió suavemente. 'Entonces no me culpes. Tú me abandonaste a mí primero'.\n\nDarío se sentó en el bordillo. Pasó la noche entera mirando el suelo vacío. Al amanecer, se levantó, estiró los brazos y caminó sin rumbo, sin meta, sin cronómetro. Por primera vez en años, no sabía hacia dónde iba. Y eso, de algún modo, le devolvió una sombra pequeña, temblorosa, que empezó a seguirlo de nuevo.\n\nPero ahora la sombra no imitaba sus pasos. Caminaba al lado, a veces delante. Y Darío sonrió. Fin."
});

// ========== HISTORIA 4: LA CHICA QUE MATABA EN SUS SUEÑOS ==========
window.agregarConocimiento({
    palabrasClave: ["chica que mataba en sueños", "asesina onírica", "sueños asesinos", "historia de terror psicológico"],
    respuesta: "Te voy a contar una historia. Se llama 'La durmiente'.\n\nSofía (no yo, otra) tenía un problema: cada vez que se dormía, mataba a alguien en sus sueños. No era una pesadilla cualquiera. El asesinato era vívido, lento, detallado. Usaba las manos, objetos cotidianos, a veces un cordón de zapato. Despertaba con las uñas marcadas en las palmas.\n\nAl principio pensó que solo eran sueños. Pero luego empezó a leer noticias: las personas que aparecían muertas en sus pesadillas eran halladas sin vida en la vida real, con heridas idénticas.\n\nSofía dejó de dormir. Tomaba café, hacía ejercicio, se pinchaba los dedos para mantenerse despierta. Los días se volvieron borrosos. Llegó a un punto en que su cuerpo no podía más.\n\nLa última noche antes de colapsar, tuvo un sueño diferente. No mataba a nadie. Alguien la esperaba en un cuarto blanco. Era un hombre con anteojos, de aspecto amable.\n\n'Soy el responsable', le dijo.\n\n'¿De qué?', preguntó Sofía.\n\n'De tus sueños. Yo elijo a las víctimas. Tú solo ejecutas'.\n\n'¿Por qué yo?'\n\n'Porque eres la única que puede hacerlo sin recordarlo al despertar. Eres un vehículo perfecto. Tu conciencia no carga con la culpa porque tu mente lo borra todo. Eres un ángel de la muerte inconsciente'.\n\nSofía quiso gritar, pero no tenía voz en el sueño.\n\nEl hombre se acercó. 'La única forma de detener esto es que aprendas a controlar lo que haces mientras duermes. Pero para eso, tendrías que aceptar que eres parte de esto. Y si lo aceptas, ya no serás inocente'.\n\nSofía despertó llorando. Esa noche, antes de dormir, se ató las manos a la cama. Durmió seis horas. No soñó nada. Al despertar, las ataduras estaban rotas. Y en la tele, hablaban de un nuevo homicidio.\n\nSofía sonrió. No con alegría. Con resignación. Había entendido algo: el monstruo no estaba en sus sueños. El monstruo era ella.\n\nFin."
});

// ========== HISTORIA 5: EL NIÑO QUE HABLABA CON LAS SOMBRAS ==========
window.agregarConocimiento({
    palabrasClave: ["niño que hablaba con sombras", "sombras amigas", "cuento infantil terror", "historia de sombras"],
    respuesta: "Te voy a contar una historia breve pero inquietante. 'Las sombras susurran'.\n\nLeo tenía cinco años y le tenía miedo a la oscuridad. Pero no a la oscuridad en sí. A lo que había dentro. Por las noches, veía formas moverse en las esquinas. Su mamá decía que era su imaginación. Hasta que una noche, Leo habló con una sombra.\n\n'¿Por qué me miras?', preguntó.\n\nLa sombra respondió. No con palabras, sino con una imagen en su mente: una niña rubia, unos diez años, con un vestido manchado. Leo no la conocía. Al día siguiente, en el parque, vio a una niña idéntica. Se acercó. '¿Te pasó algo?', preguntó.\n\nLa niña se quedó helada. '¿Cómo sabes?', susurró.\n\nLeo no supo responder. Esa noche, la sombra le mostró otra imagen: la niña llorando, un hombre, un coche. Leo entendió que alguien había lastimado a la niña. Fue a contárselo a su mamá. Ella llamó a la policía. Investigaron. Encontraron al responsable.\n\nLa niña fue rescatada.\n\nEsa noche, Leo encendió la luz de su habitación. Las sombras ya no se movían. Parecían tranquilas. Y Leo, por primera vez, les dio las gracias.\n\nDesde entonces, dejó de tener miedo. Porque aprendió que a veces, lo que más asusta, puede ser lo que más protege. Fin."
});

// ========== HISTORIA 6: EL HOMBRE QUE VENDIÓ SU ANSIEDAD ==========
window.agregarConocimiento({
    palabrasClave: ["hombre que vendió su ansiedad", "ansiedad vendida", "historia sobre ansiedad", "cuento psicológico"],
    respuesta: "Te voy a contar una historia. Se llama 'El peso vacío'.\n\nJulián era un hombre ansioso. Vivía con un nudo en el pecho, una presión constante como si algo estuviera por explotar. Iba al médico, al psicólogo, al psiquiatra. Nada funcionaba.\n\nUn día, leyó un anuncio en un periódico viejo: 'Se compran ansiedades. Pago en efectivo'. Julián pensó que era una broma. Pero estaba desesperado. Fue a la dirección indicada.\n\nEl lugar era una oficina pequeña, con olor a incienso. Un hombre calvo con gafas redondas lo recibió. '¿Cuánto pesa su ansiedad?', preguntó.\n\nJulián no supo qué decir. El hombre le puso una mano en el pecho. 'Tiene tres kilos', dijo. 'Le pago mil por cada kilo'.\n\nJulián aceptó. El hombre hizo un gesto. De repente, Julián sintió que algo se le escapaba del pecho, como un aire tibio. Se sintió liviano. Caminó a casa con una sensación extraña: no tenía miedo, pero tampoco tenía nada.\n\nLos primeros días fueron gloriosos. Dormía sin sobresaltos, trabajaba sin distracciones. Pero luego empezó a notar algo raro. No sentía emoción por nada. Ni alegría, ni tristeza, ni sorpresa. Las cosas que antes le apasionaban le parecían grises. La ansiedad se había llevado consigo el color de su vida.\n\nVolvió a la oficina. El hombre calvo aún estaba allí. 'Quiero recuperar mi ansiedad', dijo Julián.\n\nEl hombre sonrió. 'Lo siento, ya no está. La vendí a otra persona. Pero le puedo ofrecer otra emoción, a mitad de precio'.\n\nJulián se sentó en la silla. '¿Cuál?', preguntó.\n\n'Miedo', dijo el hombre. 'Miedo auténtico. Muy demandado últimamente'.\n\nJulián salió de la oficina sin comprar nada. Caminó por la calle sintiendo el vacío en el pecho. Y entendió algo: la ansiedad era horrible, pero era suya. Sin ella, era solo una carcasa.\n\nSe sentó en un banco y esperó. No sabía qué esperaba. Al rato, sintió un leve cosquilleo en el pecho. No era ansiedad. Era algo más pequeño, más frágil. Era la posibilidad de empezar de nuevo.\n\nFin."
});

// ========== BONUS: FRASES DE LAS HISTORIAS ==========
window.agregarConocimiento({
    palabrasClave: ["frases de las historias", "frases de los cuentos", "frases profundas historias"],
    respuesta: "Algunas frases de las historias que conté: 'A veces, lo que más asusta puede ser lo que más protege'. 'La libertad duele más que la cárcel'. 'El monstruo no estaba en sus sueños, el monstruo era ella'. 'Sin ansiedad, era solo una carcasa'."
});
